# This is a config for E2B sandbox template.
# You can use template ID (81rbnfr40r51pr795rov) or template name (v0-nextjs-build-atts) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("v0-nextjs-build-atts") # Sync sandbox
# sandbox = await AsyncSandbox.create("v0-nextjs-build-atts") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v0-nextjs-build-atts')

team_id = "d59a753c-c090-48d5-96aa-60a48e260711"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v0-nextjs-build-atts"
template_id = "81rbnfr40r51pr795rov"
